language: cpp
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get install libopencv-dev
  - mkdir itlPlace-build
  - cd ./itlPlace-build
  - cmake -GNinja -DPETSC_DIR=../itlPlace/3rdparty/PETSc/ -DPETSC_ARCH=ubuntu-64 -DTAO_DIR=../itlPlace/3rdparty/TAO ../itlPlace/
script: ninja -j5
notifications:
  email: false
